# 临时搬运（代替换）
options:
  merge-default-rules: false
  max-warnings: 0
# File Options
files:
  include: 'src/assets/sass/**/*.s+(a|c)ss'
  ignore:
    - 'src/assets/sass/lib/**/*.*'
    - 'src/assets/sass/base/**/*.*'
    - 'src/assets/sass/helpers/**/*.*'
    - 'src/assets/sass/generated/**/*.*'
# Rule Configuration
rules:
  force-pseudo-nesting: 2
  no-important: 2
  no-duplicate-properties: 2
  no-url-protocols: 2
  #no-extends: 2
  no-empty-rulesets: 2
  no-misspelled-properties: 2
  no-url-domains: 2
  no-transition-all: 2
  nesting-depth:
    - 2
    - max-depth: 4
  indentation:
    - 1
    - size: tab